spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootapi
    username: kpsing
    password: syspass
